export const partnerLogos = [
  { name: "Make", src: "/brand-logos/make.svg" },
  { name: "Anthropic", src: "/brand-logos/anthropic.svg" },
  { name: "OpenAI", src: "/brand-logos/openai.svg" },
  { name: "ElevenLabs", src: "/brand-logos/elevenlabs.svg" },
  { name: "Twilio", src: "/brand-logos/twilio.svg" },
  { name: "n8n", src: "/brand-logos/n8n.svg" },
  { name: "LangChain", src: "/brand-logos/langchain.svg" },
  { name: "Google Calendar", src: "/brand-logos/googlecalendar.svg" },
  { name: "Calendly", src: "/brand-logos/calendly.svg" },
  { name: "HubSpot", src: "/brand-logos/hubspot.svg" },
  { name: "Salesforce", src: "/brand-logos/salesforce.svg" },
  { name: "Pipedrive", src: "/brand-logos/pipedrive.svg" },
  { name: "Zoho", src: "/brand-logos/zoho.svg" },
  { name: "WhatsApp Business", src: "/brand-logos/whatsapp.svg" },
  { name: "Facebook Messenger", src: "/brand-logos/messenger.svg" },
  { name: "Instagram", src: "/brand-logos/instagram.svg" },
  { name: "Supabase", src: "/brand-logos/supabase.svg" },
  { name: "Vercel", src: "/brand-logos/vercel.svg" },
  { name: "DigitalOcean", src: "/brand-logos/digitalocean.svg" },
];
